---
version: '3'
services:
  zookeeper-internalad-indexer:
    image: confluentinc/cp-zookeeper:5.5.0
    logging:
      driver: none
    hostname: zookeeper
    container_name: zookeeper-internalad-indexer
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker-internalad-indexer:
    image: confluentinc/cp-kafka:5.5.0
    logging:
      driver: none
    hostname: broker
    container_name: broker-internalad-indexer
    depends_on:
      - zookeeper-internalad-indexer
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - opendistro_security.disabled=true
  internalad-indexer:
    depends_on:
      - broker-internalad-indexer
      - zookeeper-internalad-indexer
      - elasticsearch
    build: .
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SCHEDULER_ENABLED=false
