apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-internalad-indexer-os
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /prometheus
  kafka:
    pool: {{ kafka_pool }}
  openSearch:
    access: admin
    instance: intern
  env:
    - name: ADLISTENER_GROUP_ID
      value: "{{ adlistener_group_id }}"
    - name: ADLISTENER_TOPIC
      value: "{{ adlistener_topic }}"
    - name: INDEXER_ENABLED
      value: "{{ indexer_enabled }}"
    - name: INDEXER_INDEXNAME
      value: "{{ indexer_indexname }}"
    - name: INDEXER_REINDEX
      value: "{{ indexer_reindex }}"
    - name: ADLISTENER_REINDEX_GROUP_ID
      value: "{{ adlistener_reindex_group_id }}"
    - name: INDEXER_REINDEX_INDEXNAME
      value: "{{ indexer_reindex_indexname }}"
