apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-internalad-indexer
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - secret: pam-internalad-indexer
      mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: ELASTICSEARCH_URL
      value: {{ elasticsearch_url }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{ kafka_bootstrap_servers }}
  accessPolicy:
    outbound:
      rules:
        - application: stilling-opendistro-elasticsearch
