micronaut:
  application:
    name: internalad-indexer
  http:
    client:
      read-timeout: 300s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
feed:
  ad:
    url: http://localhost:9001/api/v1/ads
    pagesize: 100
    enabled: false
shedlock:
  defaults:
    lock-at-most-for: 5m
kafka:
  health:
    enabled: false
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS}
adlistener:
  group-id: internalAd
  topic: StillingIntern
  useDummyIndexer: false
indexer:
  scheduler:
    enabled: true
  ads:
    from: 24 #now-24month
