micronaut:
  application:
    name: internalad-indexer
  http:
    client:
      read-timeout: 300s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
feed:
  ad:
    url: http://localhost:9001/api/v1/ads
    pagesize: 100
shedlock:
  defaults:
    lock-at-most-for: 5m
kafka:
  health:
    enabled: false
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9092`}
adlistener:
  group-id: internalAd
  topic: StillingIntern
indexer:
  reindex-mode:
    enabled: false
    indexname: "internalad_202005"
    timestamp-from-index: true
  scheduler:
    delete:
      enabled: true
  enabled: true
  timestamp-from-index: false
  #offset-timestamp: "2019-01-01T00:00:00Z"
