micronaut:
  application:
    name: internalad-indexer-os
  server:
    thread-selection: auto
  http:
    client:
      read-timeout: 300s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
adlistener:
  topic: teampam.stilling-intern-1
indexer:
  scheduler:
    delete:
      enabled: true
  enabled: true
  reindex: true

