micronaut:
  application:
    name: internalad-indexer
  server:
    thread-selection: auto
  http:
    client:
      read-timeout: 300s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
feed:
  ad:
    url: http://localhost:9001/api/v1/ads
    pagesize: 100
shedlock:
  defaults:
    lock-at-most-for: 5m
adlistener:
  topic: StillingIntern
indexer:
  scheduler:
    delete:
      enabled: true
  enabled: true

