name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: build and test
        run: ./gradlew test build
      - name: build docker image
        run: |
          echo docker.pkg.github.com/$GITHUB_REPOSITORY/pam-internalad-indexer > .docker_image
          echo $(echo $GITHUB_SHA | cut -c1-7) > .docker_tag
          docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: push docker image
        run: |
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
#          docker push $(cat .docker_image):$(cat .docker_tag)
