name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: build and test
        run: ./gradlew test build
      - name: build docker image
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/pam-internalad-indexer
          IMAGE_TAG: ${{ echo GITHUB_SHA | cut -c1-7 }}
        run: |
          docker build . --pull -t $DOCKER_IMAGE:$IMAGE_TAG
#      - name: push docker image
#        run: |
#          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
#          docker push $(cat .docker_image):$(cat .docker_tag)
